# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ramblin' Jan
email: jan@ramblinjan.com
description: > # this means to ignore newlines until "baseurl:"
  "Ramblin" was a nod to my nomadic lifestyle (and my love for
  the Allman Brothers). Now it just means I talk a lot.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ramblinjan.com" # the base hostname & protocol for your site
twitter_username: ramblinjan
github_username:  ramblinjan

# Build settings
markdown: kramdown
