---
title: Ramblin' Jan
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jan@ramblinjan.com
future: true
description: '"Ramblin" was a nod to my nomadic lifestyle (and my love for the Allman
  Brothers). Now it just means I talk a lot.

'
baseurl: ''
url: http://ramblinjan.com
twitter_username: ramblinjan
github_username: ramblinjan
permalink: pretty
markdown: kramdown
